apiVersion: apps/v1
kind: Deployment
metadata:
  name: snk-deployment
  labels:
    app: snk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snk
  template:
    metadata:
      labels:
        app: snk
    spec:
      containers:
      - name: snk
        image: nginx:1.7.9
        ports:
        - containerPort: 80
