apiVersion: apps/v1
kind: Deployment
metadata:
  name: snk-deployment
  namespace: eldia
  labels:
    app: snk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snk
  template:
    metadata:
      labels:
        app: snk
    spec:
      containers:
      - name: snk
        image: nginx
        ports:
        - containerPort: 80
